### ISSUE TITLE
Opening the child pane by clicking on an item in the layout adds a horizontal scrollbar

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/malcolmjs#303]

**Comment by btester271828** [comment]
This may be an issue with the transition effect on the panels. I had a similar issue with the plot and table components since the component width is specified as 100% and the value of this seems to vary over the course of the transition effect (starting higher and reducing back down as the new panel transitions in). Since the component re-renders in the middle of the transition it sets its width to some larger value.

Disabling the panel transition on the drawer component does suppress this behaviour.
